In [ ]:
import numpy as np

1.試建立如下的二維陣列

In [ ]:
np.array([[4,7],[8,12]])

array([[ 4,  7],
       [ 8, 12]])

In [ ]:
np.array([[7.4],[6.7],[2.0]])

array([[7.4],
       [6.7],
       [2. ]])

In [ ]:
np.array([[7,4],[6,7],[9,-5]])

array([[ 7,  4],
       [ 6,  7],
       [ 9, -5]])

2.試建立一個2×3×4的全0陣列，型別為uint8

In [ ]:
np.zeros((2,3,4),dtype='uint8')

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=uint8)

3.試從數字1到20中隨機挑選10個數字，挑選過的數字不可重複挑選

In [ ]:
rg=np.random.default_rng(seed=998)
rg.choice(range(1,21),10,replace=False)

array([16,  5, 14,  9,  2,  8,  4, 20, 18, 12])

4.設a=np.array([23, 67, 54, 26, 92, 88, 53])，試回答下列各題

In [ ]:
a=np.array([23,67,54,26,92,88,53])

In [ ]:
a[0],a[2],a[5]

(23, 54, 88)

In [ ]:
a[-1],a[-2],a[-3]

(53, 88, 92)

In [ ]:
a[a>50]

array([67, 54, 92, 88, 53])

In [ ]:
a[1::2]

array([67, 26, 88])

In [ ]:
a[a%2==0]

array([54, 26, 92, 88])

In [ ]:
a[::-1]

array([53, 88, 92, 26, 54, 67, 23])

In [ ]:
b=a[2:5]
b[::-1]

array([92, 26, 54])

5.設a=np.arange(20).reshape((4, 5))，試回答下列各題

In [ ]:
a=np.arange(20).reshape((4,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a[0:3,1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
a[:,2:5]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [ ]:
a[1:4,:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a[:,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

In [ ]:
a[a%3==0]

array([ 0,  3,  6,  9, 12, 15, 18])

In [ ]:
x=[]
for i in range(4):
  for j in range(5):
    if (i+j)%2==0:
      x.append(a[i][j])

In [ ]:
b = a[a%2==0]
b[b%3!=0].size

6

6..設a=np.array([38, 43, 21, 87, 92, 55, 40, 63])，試利用花式索引提取陣列a的元素，使其提取後的結果為如下的陣列

In [ ]:
a=np.array([38,43,21,87,92,55,40,63])
#(a)
b=a.copy()
b[0:2]=21;b[2:4]=87
b[0:4]

array([21, 21, 87, 87])

In [ ]:
idx = np.array([[0,0,2,2]])
b[idx]

array([[21, 21, 87, 87]])

In [ ]:
idx = np.array([[0],[0],[2],[2]])
b[idx]

array([[21],
       [21],
       [87],
       [87]])

In [ ]:
idx = np.array([[0,4,4],[3,1,0]])
a[idx]

array([[38, 92, 92],
       [87, 43, 38]])

In [ ]:
idx = np.array([[2,4],[3,1],[5,3]])
a[idx]

array([[21, 92],
       [87, 43],
       [55, 87]])

In [ ]:
idx = np.array([[0,7],[0,7],[0,7]])
a[idx]

array([[38, 63],
       [38, 63],
       [38, 63]])

7.設a=np.array([0,1,2,3,4,5])。在下列各題中，試說明b是a的一個view或是copy，並驗證您的判斷結果

In [ ]:
a=np.array([0,1,2,3,4,5])
#(a)
b=a[3:]
print(f'(a):{b}')
#(b)
b=a[::-1]
print(f'(b):{b}')
#(c)
b = a.reshape(2,3)
print(f'(c):{b}')
#(d)
b = np.random.permutation(a)
print(f'(d):{b}')
#(e)
b = a[[0,3,4]]
print(f'(e):{b}')
print(f'b是a的copy，a不變，a陣列為{a}')

(a):[3 4 5]
(b):[5 4 3 2 1 0]
(c):[[0 1 2]
 [3 4 5]]
(d):[0 3 1 5 4 2]
(e):[0 3 4]
b是a的copy，a不變，a陣列為[0 1 2 3 4 5]


8.設 a=np.arange(12).reshape(3,4)，試回答下列各題（每個小題陣列a的內容都一樣）

In [ ]:
a=np.arange(12).reshape(3,4)
#(a)
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a[:,None,:]

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [ ]:
b=a.copy()
b.squeeze()


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])